name: throttling
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  rxdart: ^0.27.3
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
